<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Last name_SearchLastName</name>
   <tag></tag>
   <elementGuidId>fda498d5-908b-48fc-bb2e-837e282a3087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SearchLastName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SearchLastName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Last name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>39969161-a6a8-4482-b5d2-c35ba90a4c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>373b58dd-d514-4196-9932-2b59a330d830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchLastName</value>
      <webElementGuid>b2640afa-acf3-4831-8a18-efeb8714182e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchLastName</value>
      <webElementGuid>f09c56db-8255-4d51-a7f6-2c41f2c2c94c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d64b5f36-bd6a-4e35-9fd6-f7c16935cab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchLastName&quot;)</value>
      <webElementGuid>add01c10-a6d7-4d8c-8bcd-c86712f81678</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchLastName']</value>
      <webElementGuid>b69ad3ed-01b0-41fd-a423-e708fbace5d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>e62f3862-8ded-4b59-8b4e-6ee80a804df9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SearchLastName' and @name = 'SearchLastName' and @type = 'text']</value>
      <webElementGuid>5d2b51ff-1f71-44cd-aa01-3bbe2a8f50ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
