<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Email_SearchEmail</name>
   <tag></tag>
   <elementGuidId>eee04f14-b1ff-46e7-9683-58cbed437fac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SearchEmail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SearchEmail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Email&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bd738f95-7b20-47de-a384-6804fdeb7bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>bf4e1938-564c-4873-9941-18a677bb8c5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchEmail</value>
      <webElementGuid>127667c4-a4d4-461a-ab5b-eb897d58dc5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchEmail</value>
      <webElementGuid>0e7ed063-fa18-4dd1-86ef-c4623b4a3729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>7bea4e75-8d86-4919-ad80-dc7b0e7018ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchEmail&quot;)</value>
      <webElementGuid>1d83dfdb-54ad-4b3f-b54b-78d7eb4fbb6e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchEmail']</value>
      <webElementGuid>5409b16d-59e4-4520-a4cd-3d9bd018cf30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6d242a9c-25ae-4dfc-96d4-8e7f41251053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SearchEmail' and @name = 'SearchEmail' and @type = 'email']</value>
      <webElementGuid>8fd27808-8343-4d0f-bcd7-d82e1ffdf54d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
