<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First name_SearchFirstName</name>
   <tag></tag>
   <elementGuidId>8327d84e-d75b-40cc-a5bd-d41369e974ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SearchFirstName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SearchFirstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;First name&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87ba7f38-3da1-44e5-a2e5-cddbdc9903fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control text-box single-line</value>
      <webElementGuid>727601dd-c01c-46ab-a655-b26f7df45b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SearchFirstName</value>
      <webElementGuid>d6978d0e-56ca-4958-a01d-2ee14353740d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchFirstName</value>
      <webElementGuid>cc03047f-32f0-4f6a-9e15-89a18c3a1260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bec715d3-e5c7-4c1a-b161-9109b2bd9a0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SearchFirstName&quot;)</value>
      <webElementGuid>ed7c6b13-23b6-4335-8913-f52a6ec70dc4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SearchFirstName']</value>
      <webElementGuid>da14ac24-b5e3-45d1-b3d4-815826f2d767</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>3ac4b2c1-eccf-45d0-94a7-952d22506c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SearchFirstName' and @name = 'SearchFirstName' and @type = 'text']</value>
      <webElementGuid>578ba708-87c8-4167-a962-2f23bf26a3b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
