<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Gender_Gender</name>
   <tag></tag>
   <elementGuidId>b3992d00-7322-4d9a-9d82-ebb8510bcc48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Gender_Male</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Gender_Male']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Male&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a2549fe0-6593-40b9-a899-8347feadac3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>d32c09a3-5ac2-4b08-beba-b7536b5f20ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>8281a34b-a5b9-443b-a81e-917ba1af693d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>edb81e62-da64-4b36-a680-401f2628eb1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Gender_Male</value>
      <webElementGuid>a777df42-4abb-4707-bab2-1260daec3fd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>694d2c27-a62c-4421-9678-0547a0f58f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3eead0cc-7e1e-4551-a880-f08d5cd18426</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Gender_Male&quot;)</value>
      <webElementGuid>b7127e22-d4c6-4a10-92b0-18c23fddf97c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Gender_Male']</value>
      <webElementGuid>ba6c24a1-cf92-4202-9303-48588990578a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer-info']/div[2]/div[5]/div[2]/div/div/input</value>
      <webElementGuid>664d0187-6e54-4f4a-a6f7-96f66fd9283d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/input</value>
      <webElementGuid>a4ec3bf9-223f-44c6-af7e-ab546b998f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Gender' and @id = 'Gender_Male']</value>
      <webElementGuid>9100ff36-94ce-4738-8c16-a4f4206facc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
