<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Date of birth_DateOfBirth</name>
   <tag></tag>
   <elementGuidId>53c70963-5f9f-4337-bf50-9e366204cca3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#DateOfBirth</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='DateOfBirth']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Date of birth&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8062b8b2-72fa-4feb-b514-3c3a05cb97e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DateOfBirth</value>
      <webElementGuid>44338b98-a90e-4baa-b5f7-0abc826cfc9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DateOfBirth</value>
      <webElementGuid>d6a660f7-1a1b-41d8-a248-7488103b624b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>date</value>
      <webElementGuid>03819233-a99f-4f34-a6b6-af8d877c1c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>060c3696-b406-4914-89b7-f971e8a5f073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-form-interact-field-id</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>6dcf6ced-b0ab-45ae-9efa-d632df4849f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DateOfBirth&quot;)</value>
      <webElementGuid>1eff994c-7478-4ef1-8dfb-a389b3153381</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='DateOfBirth']</value>
      <webElementGuid>0ed903e0-e098-4fa9-9641-f6f456616557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='customer-info']/div[2]/div[6]/div[2]/input</value>
      <webElementGuid>d03abee5-4a4f-4511-a9b3-52e997d76dd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/input</value>
      <webElementGuid>18b04f0c-e457-4234-948a-50e84cbcbe34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'DateOfBirth' and @name = 'DateOfBirth' and @type = 'date']</value>
      <webElementGuid>61b0a6cc-dd14-4e7a-b3c0-2d7352dd1093</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
